### ISSUE TITLE
Which carriers does the parcel tracking system support ?

### ISSUE THREAD

**Issue by gelsas** [Nikita-Tsyganov/parcel-tracking-system#65]
Which carriers does the parcel tracking system support ?

**Comment by Nikita-Tsyganov** [comment]
> Which carriers does the parcel tracking system support?

Hello gelsas,


This project was built as a coding challenge.
Currently, it only supports its own database.
It does not support any other carriers nor communicates with any third-party APIs in its current state.

Let me know if you have any other questions.


Regards,
Nikita
